### ISSUE TITLE
data not saved when using `blacklist` or `whitelist` -- can't repro

### ISSUE THREAD

**Issue by vfa-khuongdv** [agilgur5/mst-persist#31]
When i add blacklist or white list, the data cannot save in local storage.

```ts
persist('@user', UserModel, {
  storage: AsyncStorage,
  jsonify: true,
  blacklist: ['state'] // IT will not save data
}).then(() => console.log('someStore has been hydrated'))
```

**Comment by agilgur5** [comment]
Without a reproduction and with so few details, there's no way to debug or troubleshoot what might be going on here.
`mst-persist` also has 100% test coverage, including for [whitelists](https://github.com/agilgur5/mst-persist/blob/94422793d11fa3aacb47fe6b30f60c69dcea0441/test/index.spec.ts#L56) and [blacklists](https://github.com/agilgur5/mst-persist/blob/94422793d11fa3aacb47fe6b30f60c69dcea0441/test/index.spec.ts#L68), so I cannot reproduce this.

It also sounds like this may be a misunderstanding of the usage documentation. Re-explaining:
Configuring `blacklist` means that the specified keys will _not_ be persisted.
Configuring `whitelist` means that _only_ the specified keys will be persisted, and nothing else.
